/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/ui/**/*.{js,jsx,ts,tsx,html}",
    "./src/ui/components/**/*.{js,jsx,ts,tsx}",
    "./src/ui/app/**/*.{js,jsx,ts,tsx,html}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  // 确保所有 Tailwind 工具类都被包含
  safelist: [
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'relative',
    'absolute',
    'w-[455px]',
    'h-[311px]',
    'bg-[rgba(3,0,16,0.7)]',
    'rounded-[19px]',
    'border',
    'border-[rgba(255,255,255,0.2)]',
    'border-solid',
    'inset-0',
    'pointer-events-none',
    'left-[425px]',
    'top-[12px]',
    'size-[20px]',
    'cursor-pointer',
    'hover:opacity-80',
    'transition-opacity',
    'block',
    'size-full',
    'h-[25.762px]',
    'left-[139px]',
    'top-[45px]',
    'w-[177px]',
    'left-[35px]',
    'top-[97px]',
    'w-[385px]',
    'text-white',
    'text-[15px]',
    'leading-[normal]',
    'not-italic',
    'left-[226.5px]',
    'top-[118px]',
    'gap-[4px]',
    'text-[#c17fff]',
    'w-[4.987px]',
    'rotate-180',
    'h-[44px]',
    'top-[166px]',
    'rounded-[12px]',
    'bg-[rgba(193,127,255,0.1)]',
    'border-[#c17fff]',
    'bg-[rgba(18,61,42,0.8)]',
    'border-[rgba(116,255,203,0.55)]',
    'left-[52.5px]',
    'top-[178px]',
    'w-[350px]',
    'bg-transparent',
    'border-none',
    'outline-none',
    'text-center',
    'placeholder:opacity-50',
    'text-[#98ffd7]',
    'placeholder:text-[#98ffd7]',
    'placeholder:text-[#c17fff]',
    'opacity-60',
    'cursor-not-allowed',
    'top-[214px]',
    'text-[#ff9c9c]',
    'text-[13px]',
    'min-h-[18px]',
    'top-[222px]',
    'rounded-[22px]',
    'bg-[rgba(255,255,255,0.12)]',
    'text-[#bebebe]',
    'opacity-75',
    'bg-[rgba(255,255,255,0.3)]',
    'hover:bg-[rgba(255,255,255,0.4)]',
    'transition-all',
    'text-[15px]',
    'top-[270px]',
    'px-[15px]',
    'py-[13px]',
    'rounded-[16px]',
    'text-[14px]',
    'leading-[21px]',
  ],
}

